version: 4
name: nn_stages

model:
  type: thunder_hammer.model.classification.resnet.resnet50
  deep_stem: True
  antialias: True
  num_classes: 54
  pretrained: False
  weights: /mnt/hdd1/learning_dumps/imagenet/rn50_stages_11/weights_stage3/_ckpt_epoch_116.ckpt

train_data:
  type: src.dali_dataset.DaliLoader
  batch_size: 256
  workers: 5
  crop_size: 224
  color_twist: True
  min_area: 0.2

val_data:
  type: src.dataset.HakunaPrefetchedLoader
  batch_size: 32
  workers: 12
  long_side: 320

mixup:
  type: thunder_hammer.mixup.NoMixUp

scheduler:
  warmup_epoch: 1
  warmup: True
  period: 72

sync_bn: True
no_bn_weight_decay: False

optimizer:
  weight_decay: 0.0001

stages:
#  stage1:
#    freeze: 4
#    train_data:
#      crop_size: 192
#      workers: 12
#    optimizer:
#      lr: 0.01
#    trainer:
#      max_epochs: 3
#    scheduler:
#      period: 3

  stage2:
    freeze: 1
    train_data:
      crop_size: 224
      batch_size: 192
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 1
      period: 20

  stage3:
    freeze: 0
    train_data:
      crop_size: 224
      batch_size: 160
      color_twist: False
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 1
      period: 20


weights: /mnt/ssd1/learning_dumps/wild/rx50_stages_2/weights_stage2/_ckpt_epoch_5.ckpt
tta: mirror