version: 1
name: rn50_stages

model:
  type: thunder_hammer.model.classification.resnet.resnet50
  pretrained: imagenet
  num_classes: 54

data:
  type: thunder_hammer.dataset.dali.DaliLoader
  workers: 4
  batch_size: 256
  color_twist: True
  filelist: 'tables'
  min_area: 0.2

mixup:
  type: thunder_hammer.mixup.NoMixUp

scheduler:
  warmup_epoch: 1
  warmup: True
  period: 72

sync_bn: True
no_bn_weight_decay: False

optimizer:
  weight_decay: 0.0001

freeze: 1

stages:
  stage1:
    data:
      crop_size: 192
    optimizer:
      lr: 0.01
    trainer:
      max_epochs: 20
    scheduler:
      period: 40
    freeze: 2

  stage2:
    data:
      crop_size: 224
      batch_size: 256
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 0
      period: 20

  stage3:
    data:
      crop_size: 224
      batch_size: 160
      color_twist: False
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 10
    scheduler:
      warmup_epoch: 0
      period: 10
    freeze: 0
