version: 5
name: rn50aa_stages

model:
  type: thunder_hammer.model.classification.resnet.resnet50
  deep_stem: True
  antialias: True
  num_classes: 54
  pretrained: False
  weights: /mnt/hdd1/learning_dumps/wild/nn_stages_4/weights_stage2/_ckpt_epoch_5.ckpt

train_data:
  type: thunder_hammer.dataset.dali.DaliLoader
  workers: 6
  batch_size: 128
  color_twist: True
#  filelist: 'tables'
  min_area: 0.2

val_data:
  type: src.dataset.HakunaPrefetchedLoader
  batch_size: 32
  workers: 12
  long_side: 256

mixup:
  type: thunder_hammer.mixup.NoMixUp

scheduler:
  warmup_epoch: 1
  warmup: True
  period: 72

sync_bn: True
no_bn_weight_decay: False

optimizer:
  weight_decay: 0.0001

stages:
  stage2:
    train_data:
      crop_size: 224
      batch_size: 128
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 0
      period: 20

  stage3:
    freeze: 0
    train_data:
      crop_size: 224
      batch_size: 160
      color_twist: False
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 1
      period: 20


weights: /mnt/ssd1/learning_dumps/wild/rx50_stages_2/weights_stage2/_ckpt_epoch_5.ckpt
tta: mirror