version: 2
name: rx101_stages

model:
  type: thunder_hammer.model.classification.resnet.resnext101_32x8d
  pretrained: imagenet_ig
  num_classes: 54

train_data:
  type: src.dataset.HakunaPrefetchedLoader
  workers: 5
  val_batch: 16
  batch_size: 256
  long_side: 256
  color_twist: True
  min_area: 0.2

val_data:
  type: src.dataset.HakunaPrefetchedLoader
  workers: 5
  batch_size: 16
  long_side: 320
  color_twist: True
  min_area: 0.2

mixup:
  type: thunder_hammer.mixup.NoMixUp

scheduler:
  warmup_epoch: 1
  warmup: True
  period: 72

sync_bn: True
no_bn_weight_decay: False

optimizer:
  weight_decay: 0.0001

freeze: 1

stages:
  stage2:
    data:
      crop_size: 224
      batch_size: 256
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 20
    scheduler:
      warmup_epoch: 0
      period: 20

  stage3:
    data:
      crop_size: 224
      batch_size: 160
      color_twist: False
    optimizer:
      lr: 0.005
    trainer:
      max_epochs: 10
    scheduler:
      warmup_epoch: 0
      period: 10
    freeze: 0

weights:
  - /mnt/ssd1/learning_dumps/wild/rx101_stages_2/weights_stage2/_ckpt_epoch_8.ckpt
#  - /mnt/ssd1/learning_dumps/wild/rx101_stages_2/weights_stage2/_ckpt_epoch_5.ckpt
  - /mnt/ssd1/learning_dumps/wild/rx101_stages_4/weights_stage3/_ckpt_epoch_12.ckpt